const STATUS_ACTIVE = "ACTIVE";
const STATUS_INACTIVE = "INACTIVE";
const STATUS_CANCELLED = "CANCELLED";
const TRANSACTION_TYPE_WRITE_OFF = "WRITE_OFF";
const TRANSACTION_WAIVER = "WAIVER";
const PAYMENT_METHOD_MANUAL = "MANUAL";

module.exports = {
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_CANCELLED,
  TRANSACTION_TYPE_WRITE_OFF,
  TRANSACTION_WAIVER,
  PAYMENT_METHOD_MANUAL,
};

module.exports.ENUM_TRANSACTION_TYPES = [
  TRANSACTION_TYPE_WRITE_OFF,
  TRANSACTION_WAIVER,
];

module.exports.ENUM_PAYMENT_METHODS = [PAYMENT_METHOD_MANUAL];

module.exports.ENUM_STATUS = [STATUS_ACTIVE, STATUS_INACTIVE, STATUS_CANCELLED];
