const STATUS_ACTIVE = "ACTIVE";
const STATUS_INACTIVE = "INACTIVE";
const STATUS_CANCELLED = "CANCELLED";
const TRANSACTION_TYPE_WRITE_OFF = "WRITE_OFF";
const TRANSACTION_WAIVER = "WAIVER";
const TRANSACTION_PAYMENT = "PAYMENT";
const PAYMENT_METHOD_MANUAL = "MANUAL";
const PAYMENT_METHOD_CASH = "CASH";
const PAYMENT_METHOD_REC_BANK = "REC_BANK";
const PAYMENT_METHOD_TOTZ_BANK = "TOTZ_BANK";
const PAYMENT_METHOD_REC_CREDIT_CARD = "REC_CREDIT_CARD";
const PAYMENT_METHOD_TOTZ_CREDIT_CARD = "TOTZ_CREDIT_CARD";

module.exports = {
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_CANCELLED,
  TRANSACTION_TYPE_WRITE_OFF,
  TRANSACTION_WAIVER,
  TRANSACTION_PAYMENT,
  PAYMENT_METHOD_MANUAL,
};

module.exports.ENUM_TRANSACTION_TYPES = [
  TRANSACTION_TYPE_WRITE_OFF,
  TRANSACTION_WAIVER,
  TRANSACTION_PAYMENT
];

module.exports.ENUM_PAYMENT_METHODS = [
  PAYMENT_METHOD_CASH,
  PAYMENT_METHOD_REC_BANK,
  PAYMENT_METHOD_TOTZ_BANK,
  PAYMENT_METHOD_REC_CREDIT_CARD,
  PAYMENT_METHOD_TOTZ_CREDIT_CARD,
  PAYMENT_METHOD_MANUAL,
];

module.exports.ENUM_STATUS = [STATUS_ACTIVE, STATUS_INACTIVE, STATUS_CANCELLED];
