const STATUS_ACTIVE = "ACTIVE";
const STATUS_INACTIVE = "INACTIVE";
const STATUS_CANCELLED = "CANCELLED";

module.exports = {
  STATUS_ACTIVE,
  STATUS_INACTIVE,
  STATUS_CANCELLED,
};

module.exports.ENUM_STATUS = [STATUS_ACTIVE, STATUS_INACTIVE, STATUS_CANCELLED];
