const PAY_FREQUENCY_ANNUAL = "PAY_FREQUENCY_ANNUAL";
const CHARGES_CLUB_MEMBERSHIP_ID = "CLUB_MEMBERSHIP_ID";

module.exports = {
  PAY_FREQUENCY_ANNUAL,
  CHARGES_CLUB_MEMBERSHIP_ID,
};

module.exports.ENUM_CHARGES = [CHARGES_CLUB_MEMBERSHIP_ID];

module.exports.ENUM_PAY_FREQUENCY = [PAY_FREQUENCY_ANNUAL];
