const PAY_FREQUENCY_ANNUAL = "PAY_FREQUENCY_ANNUAL";
const CHARGES_CLUB_MEMBERSHIP_ID = "CLUB_MEMBERSHIP_ID";

module.exports = {
  PAY_FREQUENCY_ANNUAL,
  CHARGES_CLUB_MEMBERSHIP_ID,
};

module.exports.ENUM_BUSINESS_FINANCE = [
  "CASH",
  "REC_BANK",
  "TOTZ_BANK",
  "REC_CREDIT_CARD",
  "TOTZ_CREDIT_CARD",
];

module.exports.ENUM_CHARGES = [CHARGES_CLUB_MEMBERSHIP_ID];

module.exports.ENUM_PAY_FREQUENCY = [PAY_FREQUENCY_ANNUAL];
