const PAY_FREQUENCY_ANNUAL = "ANNUAL";
const PAY_FREQUENCY_MONTHLY = "MONTHLY";
const PAY_FREQUENCY_TRIAL = "TRIAL";
const CLASS_STATUS_ACTIVE = "ACTIVE";
const CLASS_STATUS_INACTIVE = "INACTIVE";
const REGISTRATION_FORM_STANDARD = "STANDARD";
const ENROLMENT_CONTROL_AGE = "AGE";
const ENROLMENT_CONTROL_GENDER = "GENDER";
const TERM_STATUS_ACTIVE = "ACTIVE";
const TERM_STATUS_INACTIVE = "INACTIVE";

module.exports.ENUM_PAY_FREQUENCY = [
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
];

module.exports.ENUM_STATUS = [CLASS_STATUS_ACTIVE, CLASS_STATUS_INACTIVE];

module.exports = {
  ENROLMENT_CONTROL_AGE,
  ENROLMENT_CONTROL_GENDER,
  PAY_FREQUENCY_ANNUAL,
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
  CLASS_STATUS_ACTIVE,
  CLASS_STATUS_INACTIVE,
  REGISTRATION_FORM_STANDARD,
};

module.exports.ENUM_REGISTRATION_FORM = [REGISTRATION_FORM_STANDARD];

module.exports.ENUM_ENROLMENT_CONTROLS = [
  ENROLMENT_CONTROL_AGE,
  ENROLMENT_CONTROL_GENDER,
];

module.exports.ENUM_TERM_STATUS = [TERM_STATUS_ACTIVE, TERM_STATUS_INACTIVE];
