const TYPE_PERCENTAGE = "PERCENTAGE";

const ENUM_DISCOUNT_TYPES = [TYPE_PERCENTAGE];

const ACTIVE_STATUS = "ACTIVE";
const INACTIVE_STATUS = "INACTIVE";
const ENUM_STATUS = [ACTIVE_STATUS, INACTIVE_STATUS];

module.exports = {
  TYPE_PERCENTAGE,
  ENUM_DISCOUNT_TYPES,
  ACTIVE_STATUS,
  INACTIVE_STATUS,
  ENUM_STATUS,
};
