const STATUS_TRIAL_ENROLLED = "TRIAL_ENROLLED";
const STATUS_ENROLLED = "ENROLLED";
const STATUS_WAITLISTED = "WAITLISTED";
const STATUS_DROPPED = "DROPPED";
const STATUS_SUSPEND = "SUSPEND";
const STATUS_RETURN_FROM_SUSPENSION = "RETURN_FROM_SUSPENSION";

const DISCONTINUATION_REASON_DROPPED = "DROPPED";
const DISCONTINUATION_REASON_CLASS_TRANSFER = "CLASS_TRANSFER";

module.exports = {
  STATUS_TRIAL_ENROLLED,
  STATUS_ENROLLED,
  STATUS_WAITLISTED,
  STATUS_DROPPED,
  STATUS_SUSPEND,
  STATUS_RETURN_FROM_SUSPENSION,
  DISCONTINUATION_REASON_DROPPED,
  DISCONTINUATION_REASON_CLASS_TRANSFER,
};

module.exports.ENUM_ENROLLED_STATUS = [
  STATUS_TRIAL_ENROLLED,
  STATUS_ENROLLED,
  STATUS_WAITLISTED,
  STATUS_DROPPED,
  STATUS_SUSPEND,
  STATUS_RETURN_FROM_SUSPENSION,
];

module.exports.ENUM_TRANSFER_ALLOWED = [
  STATUS_ENROLLED,
  STATUS_RETURN_FROM_SUSPENSION,
];

module.exports.ENUM_TRANSFER_NOT_ALLOWED = [
  STATUS_TRIAL_ENROLLED,
  STATUS_WAITLISTED,
  STATUS_DROPPED,
  STATUS_SUSPEND,
];

module.exports.ENUM_DISCONTINUATION_REASON = [
  DISCONTINUATION_REASON_DROPPED,
  DISCONTINUATION_REASON_CLASS_TRANSFER,
];
