/**
 * WARNING: do not update this values,
 * if any changes required in functional privileges
 * make the functional privileges as object,
 * keys should remain the same, values can then be updated
 * keys will be used for application,
 * values can be used for displaying in ui
 */
const BUSINESS_DEFINITION = "BUSINESS_DEFINITION";
const BUSINESS_FINANCE = "BUSINESS_FINANCE";
const CLASS_ATTENDANCE = "CLASS_ATTENDANCE";
const CLASS_CATEGORY = "CLASS_CATEGORY";
const CLASS_DEFINITION = "CLASS_DEFINITION";
const CLASS_ENROLMENT = "CLASS_ENROLMENT";
const DISCOUNT = "DISCOUNT";
const EVALUATION_SCHEME = "EVALUATION_SCHEME";
const MEMBERS = "MEMBERS";
const MEMBER_EVALUATION = "MEMBER_EVALUATION";
const MEMBER_ENROLMENTS = "MEMBER_ENROLMENTS";
const PROGRESS_RECORD = "PROGRESS_RECORD";
const SESSION_DEFINITION = "SESSION_DEFINITION";
const TERM = "TERM";
const USERS = "USERS";
const ROLES = "ROLES";
const FINANCE_CHARGES = "FINANCE_CHARGES";
const FINANCE_TRANSACTIONS = "FINANCE_TRANSACTIONS";
//const FINANCE_DISCOUNT = "FINANCE_DISCOUNT";

module.exports = {
  BUSINESS_DEFINITION,
  BUSINESS_FINANCE,
  CLASS_ATTENDANCE,
  CLASS_CATEGORY,
  CLASS_DEFINITION,
  CLASS_ENROLMENT,
  DISCOUNT,
  EVALUATION_SCHEME,
  MEMBERS,
  MEMBER_EVALUATION,
  MEMBER_ENROLMENTS,
  PROGRESS_RECORD,
  SESSION_DEFINITION,
  TERM,
  USERS,
  ROLES,
  FINANCE_CHARGES,
  FINANCE_TRANSACTIONS,
  //FINANCE_DISCOUNT,
};
