const PROGRESS_NOT_STARTED = "NOT_STARTED";
const PROGRESS_IN_PROGRESS = "IN_PROGRESS";
const PROGRESS_AWARDED = "AWARDED";

module.exports = {
  PROGRESS_NOT_STARTED,
  PROGRESS_IN_PROGRESS,
  PROGRESS_AWARDED,
};

module.exports.SKILL_PROGRESS_STATUS = [
  PROGRESS_NOT_STARTED,
  PROGRESS_IN_PROGRESS,
  PROGRESS_AWARDED,
];

module.exports.UPDATE_SKILL_PROGRESS_STATUS = [
  PROGRESS_IN_PROGRESS,
  PROGRESS_AWARDED,
];
