#!/usr/bin/bash
MONGODB_BACKUP_DEV_URL_ENV_LINE=$(grep MONGODB_BACKUP_DEV_URL .env)
MONGODB_BACKUP_DEV_URL=$(echo $MONGODB_BACKUP_DEV_URL_ENV_LINE | cut -d'=' -f2-)
echo $MONGODB_BACKUP_DEV_URL
mongorestore --uri $MONGODB_BACKUP_DEV_URL