module.exports.ENUM_BUSINESS_TYPE = [
  "LIMITED_COMPANY",
  "LIMITED_LIABILITY_PARTNERSHIP",
  "SOLE_TRADER",
];

module.exports.ENUM_CLASSES_STATUS = ["ACTIVE", "INACTIVE"];

module.exports.SKILL_PROGRESS_STATUS = [
  "NOT_STARTED",
  "IN_PROGRESS",
  "ATTAINED",
];
module.exports.ENUM_PAY_FREQUENCY = ["Monthly", "Annual"];

module.exports.FUNCTIONAL_PRIVILEDGES = [
  "ACTIVITY_DEFINITION",
  "ACTIVITY_ENROLMENT",
  "ACTIVITY_ATTENDANCE",
  "PROGRESS_RECORD",
];

module.exports.ADDRESS_TYPE = ["PRIMARY", "SECONDARY"];

module.exports.RELATIONSHIPS = [
  "FRIEND",
  "GRAND_PARENT",
  "UNCLE",
  "AUNT",
  "OTHER",
];
module.exports.RELATIONSHIPS = [
  "FATHER",
  "MOTHER",
  "SON",
  "DAUGHTER",
  "HUSBAND",
  "WIFE",
  "BROTHER",
  "SISTER",
  "UNCLE",
  "AUNT",
  "NEPHEW",
  "NIECE",
  "COUSIN",
];
module.exports.ENUM_DATA_PRIVILEDGES_TYPE = ["ALL", "ONE"];
module.exports.ENUM_ENUM_USER_TYPES = ["COACH"];
module.exports.ENUM_EVALUATION_SCHEME_STATUS = ["active", "inactive"];
module.exports.ENUM_ENROLLED_STATUS = [
  "ENROLLED",
  "WAITLISTED",
  "DROPPED",
  "SUSPEND",
  "RETURN_FROM_SUSPENSION",
];
module.exports.ENUM_DISCONTINUATION_REASON = ["CLASS_TRANSFER", "CANCELLED"];
module.exports.ENUM_DAY = ["MON", "TUE", "WEB", "THU", "FRI", "SAT"];
module.exports.ENUM_SESSION_STATUS = [
  "NOT_OPEN_FOR_ENROLMENT",
  "OPEN_FOR_ENROLMENT",
  "WAITLIST_ENROLMENT",
  "CLOSED_FOR_ENROLMENT",
  "CANCEL",
];
