/**
 * THIS FILE IS TO BE USED ONLY FOR CONSTANTS RELATED TO BUSINESS
 */

const BUSINESS_STATUS_ACTIVE = "ACTIVE";
const BUSINESS_STATUS_INACTIVE = "INACTIVE";
const BUSINESS_TYPE_LIMITED_COMPANY = "LIMITED_COMPANY";
const BUSINESS_TYPE_LIMITED_LIABILITY_PARTNERSHIP =
  "LIMITED_LIABILITY_PARTNERSHIP";
const BUSINESS_TYPE_SOLE_TRADER = "SOLE_TRADER";
const PAY_FREQUENCY_ANNUAL = "ANNUAL";
const PAY_FREQUENCY_MONTHLY = "MONTHLY";
const PAY_FREQUENCY_TRIAL = "TRIAL";

module.exports.ENUM_BUSINESS_TYPE = [
  BUSINESS_TYPE_LIMITED_COMPANY,
  BUSINESS_TYPE_LIMITED_LIABILITY_PARTNERSHIP,
  BUSINESS_TYPE_SOLE_TRADER,
];
module.exports.ENUM_PAY_FREQUENCY = [
  PAY_FREQUENCY_ANNUAL,
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
];
module.exports.ENUM_STATUS = [BUSINESS_STATUS_ACTIVE, BUSINESS_STATUS_INACTIVE];

module.exports = {
  BUSINESS_STATUS_ACTIVE,
  BUSINESS_STATUS_INACTIVE,
  BUSINESS_TYPE_LIMITED_COMPANY,
  BUSINESS_TYPE_LIMITED_LIABILITY_PARTNERSHIP,
  BUSINESS_TYPE_SOLE_TRADER,
  PAY_FREQUENCY_ANNUAL,
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
};
