const PAY_FREQUENCY_ANNUAL = "ANNUAL";
const PAY_FREQUENCY_MONTHLY = "MONTHLY";
const PAY_FREQUENCY_TRIAL = "TRIAL";

module.exports.ENUM_PAY_FREQUENCY = [
  PAY_FREQUENCY_ANNUAL,
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
];

module.exports = {
  PAY_FREQUENCY_ANNUAL,
  PAY_FREQUENCY_MONTHLY,
  PAY_FREQUENCY_TRIAL,
};
