const {
  BUSINESS_DEFINITION,
  CLASS_ATTENDANCE,
  CLASS_CATEGORY,
  CLASS_DEFINITION,
  CLASS_ENROLMENT,
  EVALUATION_SCHEME,
  MEMBERS,
  PROGRESS_RECORD,
  SESSION_DEFINITION,
  SESSION_TERM,
  USER,
} = require("./pages");

const { CRUD } = require("./rest");

const FUNCTIONAL_PRIVILEGES = [
  BUSINESS_DEFINITION,
  CLASS_DEFINITION,
  CLASS_ENROLMENT,
  CLASS_ATTENDANCE,
  SESSION_DEFINITION,
  CLASS_CATEGORY,
  PROGRESS_RECORD,
  MEMBERS,
  USER,
  SESSION_TERM,
  EVALUATION_SCHEME,
];

const DATA_PRIVILEGES_ALL = "ALL";
const DATA_PRIVILEGES_LIST = "LIST";
const DATA_PRIVILEGES_TYPE = [DATA_PRIVILEGES_ALL, DATA_PRIVILEGES_LIST];
const STARTS_WITH_FILTER = "STARTS_WITH";
const EQUALS_FILTER = "EQUALS";
const FILTER_TYPES = [STARTS_WITH_FILTER, EQUALS_FILTER];
const EVALUATION_STATUS_ACTIVE = "ACTIVE";
const EVALUATION_STATUS_INACTIVE = "INACTIVE";
const EVALUATION_STATUS = [
  EVALUATION_STATUS_ACTIVE,
  EVALUATION_STATUS_INACTIVE,
];
const ADDRESS_TYPE = ["PRIMARY", "SECONDARY"];
const RELATIONSHIPS = ["FRIEND", "GRAND_PARENT", "UNCLE", "AUNT", "OTHER"];
const ENUM_ENROLLED_STATUS = [
  "TRIAL_ENROLLED",
  "ENROLLED",
  "WAITLISTED",
  "DROPPED",
  "SUSPEND",
  "RETURN_FROM_SUSPENSION",
];

const ENUM_DISCONTINUATION_REASON = ["DROPPED", "CLASS_TRANSFER", "CANCELLED"];
const SKILL_PROGRESS_STATUS = ["NOT_STARTED", "IN_PROGRESS", "AWARDED"];
const ENUM_CLASSES_STATUS = ["ACTIVE", "INACTIVE"];
const ENUM_CLASSES_NAME = ["AGE", "GENDER"];
const ENUM_CLASSES_TYPE = ["SELECT", "RADIO"];
const TERM_STATUS_ACTIVE = "active";
const TERM_STATUS_INACTIVE = "inactive";
const TERM_STATUS = [TERM_STATUS_ACTIVE, TERM_STATUS_INACTIVE];

const PROGRESS_STATUS = ["NOT_STARTED", "IN_PROGRESS", "ATTAINED"];
const ENUM_USER_TYPES = ["BUSINESS_ADMIN", "COACH"];

module.exports = {
  ADDRESS_TYPE,
  CRUD,
  DATA_PRIVILEGES_ALL,
  DATA_PRIVILEGES_LIST,
  DATA_PRIVILEGES_TYPE,
  ENUM_CLASSES_STATUS,
  ENUM_DISCONTINUATION_REASON,
  ENUM_ENROLLED_STATUS,
  EQUALS_FILTER,
  EVALUATION_STATUS_ACTIVE,
  EVALUATION_STATUS_INACTIVE,
  EVALUATION_STATUS,
  FILTER_TYPES,
  FUNCTIONAL_PRIVILEGES,
  PROGRESS_STATUS,
  RELATIONSHIPS,
  STARTS_WITH_FILTER,
  SKILL_PROGRESS_STATUS,
  TERM_STATUS,
  ENUM_CLASSES_NAME,
  ENUM_CLASSES_TYPE,
  ENUM_USER_TYPES,
};
